/*
 * Event_Data_Delivery.c
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 *
 */
#include "lwm2m_object_options.h"

#include "Event_Data_Delivery.h"
#include "data_delivery_base.h"
#include "event_and_alarm_base.h"
#include "Delivery_Schedule.h"
#include "log.h"
#include <string.h>


#ifndef DEBUG_EVENT_DATA_DELIVERY
#undef log_debug
#define log_debug(...)
#endif



#define EVENT_DATA_DELIVERY_DEFAULT_NAME "Default Event Data delivery"

extern lwm2m_object_declaration_t Event_Data_Delivery_object_declaration;

//By default, this should link to all Event Data objects, including meter vendor specific events.
//This reference design only implements the water meter high pressure alarm object.
static lwm2m_object_link_t default_event_links[] = {
  { 8024, 0}
};

//
// This function is called when the scheduler wants us to report data.
void Event_Data_Delivery_report(lwm2m_object_link_t delivery_object, lwm2m_object_link_t schedule, void *user_data)
{
  for (uint16_t i = 0; i < MAX_MULTIPLE_RESOURCES; i++)
  {
    if (Event_Data_Delivery_Event_Data_Links_is_set(delivery_object.instance_id, i))
    {
      lwm2m_object_link_t event_object;
      Event_Data_Delivery_Event_Data_Links_get(delivery_object.instance_id, i, &event_object);

      //event_object now points to an object that this delivery object must deliver the payload from. So we must
      //generate the payload and set it onto the value field for this resource.
      uint8_t *payload;
      size_t payload_length;
      event_and_alarm_base_Latest_Payload_get_for_object_instance(event_object, &payload, &payload_length);

      //set the payload onto the resource. Note we do NOT notify when we set this resource because we want to
      //get a confirmation and the default notify does not request confirmation, AND we want to
      //aggregate all payloads before notifying the change of the resource.
      Event_Data_Delivery_Latest_Eventlog_set(delivery_object.instance_id, i, payload, payload_length, false);
    }
  }

  //FIXME: The hard coded resource ID '2' needs to be replaced with a constant generated by the code generator.
  lwm2m_object_base_resource_changed(Event_Data_Delivery_get_lwm2m_object(), delivery_object.instance_id, 2, true);
}

//called when the schedule object link is changed.
uint8_t Event_Data_Delivery_Schedule_changed(uint16_t instance)
{
  lwm2m_object_link_t delivery_object;
  delivery_object.instance_id = instance;
  delivery_object.object_id = Event_Data_Delivery_get_lwm2m_object()->objID;

  data_delivery_base_remove_handlers(delivery_object);

  lwm2m_object_link_t schedule;
  Event_Data_Delivery_Schedule_get(instance,  &schedule);

  data_delivery_base_add_handler(delivery_object, schedule, Event_Data_Delivery_report, 0);
  return COAP_NO_ERROR;
}

//called when the payload delivery has been confirmed by the server, this is where we must
//advance the delivered pointer.
uint8_t Event_Data_Delivery_Latest_Eventlog_confirmed(lwm2m_object_t *object, uint16_t instance, uint16_t resource_id)
{
   log_debug("Confirming Interval Data Delivery Latest Payload on instance %d", instance);
  //iterate over each object link and call the confirmed handler for each interval object
  for (uint16_t i = 0; i < MAX_MULTIPLE_RESOURCES; i++)
  {
    if (Event_Data_Delivery_Event_Data_Links_is_set(instance, i))
    {
      lwm2m_object_link_t event_object;
      Event_Data_Delivery_Event_Data_Links_get(instance, i, &event_object);

      event_and_alarm_base_alarm_Latest_Payload_confirmed_for_object_instance(event_object);
    }
  }

  lwm2m_object_link_t schedule;
  Event_Data_Delivery_Schedule_get(instance, &schedule);
  Delivery_Schedule_confirm(schedule.instance_id);
  return COAP_NO_ERROR;
}

__static void Event_Data_Delivery_object_initialise_instance(uint16_t instance_id)
{
  log_info("Initialising Event Data Delivery object with instance id of %u", instance_id);

  //register that the payload resource is a confirmable resource
  lwm2m_object_base_register_confirmable(Event_Data_Delivery_get_lwm2m_object(), instance_id, 2);
}

//
// This function is called by the lwm2m stack when a new instance is created.
void Event_Data_Delivery_instance_created(uint16_t instance_id)
{
  Event_Data_Delivery_object_initialise_instance(instance_id);
}

void Event_Data_Delivery_object_initialise(void)
{
  Event_Data_Delivery_initialise();

  Event_Data_Delivery_object_declaration.resources[2].confirmed = Event_Data_Delivery_Latest_Eventlog_confirmed;

  Event_Data_Delivery_create_instance(0);

  //set defaults for instance 0 per the SEW specification
  Event_Data_Delivery_Name_set(0, EVENT_DATA_DELIVERY_DEFAULT_NAME, strlen(EVENT_DATA_DELIVERY_DEFAULT_NAME), false);

  for (int i = 0; i < sizeof(default_event_links)/sizeof(lwm2m_object_link_t); i++)
  {
    Event_Data_Delivery_Event_Data_Links_set(0, i, default_event_links[i], false);
  }

  lwm2m_object_link_t schedule_object_link = { 8002, 0};
  Event_Data_Delivery_Schedule_set(0, schedule_object_link, false);
}

void Event_Data_Delivery_register(lwm2m_context_t *context)
{
  Event_Data_Delivery_register_object(context);
  Event_Data_Delivery_register_instance(0);
  //register that the payload resource is a confirmable resource
  lwm2m_object_base_register_confirmable(Event_Data_Delivery_get_lwm2m_object(), 0, 2);
}
